version: '3.8'

services:
  test_app:
    restart: "no"
    build:
      dockerfile: ./Dockerfile-test
    networks:
      - ${DB_NETWORK}
      - ${GRPC_NETWORK}
    env_file:
      - .test_env

  test_grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: "no"
    env_file:
      - .test_env
    networks:
      - ${DB_NETWORK}
      - ${GRPC_NETWORK}

  test_db:
    image: postgres:14.5
    restart: "no"
    networks:
      - ${DB_NETWORK}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

networks:
  ${DB_NETWORK}:
  ${GRPC_NETWORK}:
