services:
  test_app:
    restart: no
    build:
      dockerfile: ./Dockerfile-test
    networks:
      - lawly_db
    env_file:
      - .test_env
    ports:
      - "8800:80"

  test_db:
    image: postgres:14.5
    restart: always
    networks:
      - lawly_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

networks:
  lawly_db:
