version: '3.8'

services:
  app:
    restart: always
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - lawly_prod_db
      - lawly_prod_grpc
    env_file:
      - app/.env
    ports:
      - "127.0.0.1:8820:80"

  user_prod_grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: always
    ports:
      - "127.0.0.1:50071:50051"
    env_file:
      - app/.env
    networks:
      - lawly_prod_grpc
      - lawly_prod_db
    depends_on:
      - app

networks:
  lawly_prod_grpc:
    external: true
  lawly_prod_db:
    external: true
