services:
  app:
    restart: always
    depends_on:
      - db
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - lawly_db
      - lawly_grpc
    env_file:
      - app/.env
    ports:
      - "8800:80"

  grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: always
    ports:
      - "50051:50051"
    env_file:
      - app/.env
    networks:
      - lawly_db
      - lawly_grpc
    depends_on:
      - app

  db:
    image: postgres:14.5
    restart: always
    networks:
      - lawly_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./lawly_db_data:/var/lib/postgresql/data
    ports:
      - "5458:5432"

networks:
  lawly_grpc:
    external: true
  lawly_db:
