version: '3.8'

services:
  app:
    restart: always
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - ${DB_NETWORK}
      - ${GRPC_NETWORK}
    env_file:
      - app/.env
    ports:
      - "${APP_PORT:-127.0.0.1:8800:80}"

  user_grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: always
    ports:
      - "${GRPC_PORT:-127.0.0.1:50051:50051}"
    env_file:
      - app/.env
    networks:
      - ${GRPC_NETWORK}
      - ${DB_NETWORK}
    depends_on:
      - app

networks:
  ${GRPC_NETWORK}:
    external: true
  ${DB_NETWORK}:
    external: true
