services:
  test_app:
    restart: "no"
    build:
      dockerfile: ./Dockerfile-test
    networks:
      - lawly_db
      - lawly_grpc
    env_file:
      - .test_env

  test_grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: "no"
    env_file:
      - .test_env
    networks:
      - lawly_db
      - lawly_grpc

  test_db:
    image: postgres:14.5
    restart: "no"
    networks:
      - lawly_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

networks:
  lawly_db:
  lawly_grpc:
