version: '3.8'

services:
  app:
    restart: always
    depends_on:
      - db
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - ${DB_NETWORK}
      - ${GRPC_NETWORK}
    env_file:
      - app/.env
    ports:
      - "${APP_PORT}"

  user_grpc_service:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    restart: always
    ports:
      - "${GRPC_PORT}"
    env_file:
      - app/.env
    networks:
      - ${DB_NETWORK}
      - ${GRPC_NETWORK}
    depends_on:
      - app

  db:
    image: postgres:14.5
    restart: always
    networks:
      - ${DB_NETWORK}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./lawly_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}"

networks:
  ${GRPC_NETWORK}:
    external: true
  ${DB_NETWORK}:
