register_user_description = "Создание нового аккаунта пользователя в системе"
login_user_description = "Аутентификация существующего пользователя"
logout_user_description = "Завершение сессии пользователя (инвалидация токена)"
refresh_token_description = "Обновление токенов доступа и обновления"
login_lawyer_description = "Авторизация юриста"
