name: Deploy to Development

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy from existing project directory
        run: |
          cd /home/lawly/auth
          git fetch --all
          git reset --hard origin/development
          docker compose -f docker-compose.yml -p dev up -d --build
