name: Deploy to Production

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy from existing project directory
      run: |
        cd /home/lawly/auth
        git fetch --all
        git reset --hard origin/development
        docker-compose up -d --build
